tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/cask"
brew "bash-completion"
brew "exercism"
brew "git"
brew "haskell-stack"
brew "mongodb", restart_service: true
brew "nvm"
brew "thefuck"
brew "yarn", args: ["without-node"]
cask "atom"
cask "discord"
cask "folx"
cask "google-chrome"
cask "insomniax"
cask "ngrok"
cask "postman"
cask "robo-3t"
cask "skype"
cask "slack"
cask "steam"
cask "telegram-desktop"
cask "visual-studio-code"
cask "vlc"
